export const SPECIES_LIST = [
  'Cane', 'Gatto', 'Coniglio', 'Criceto', 'Topo', 'Ratto',
  'Cavia', 'Furretto', 'Pappagallo', 'Canarino', 'Tartaruga',
  'Serpente', 'Iguana', 'Pesce', 'Cavallo', 'Capra', 'Pecora',
]

export const SPECIES_EMOJI: Record<string, string> = {
  'Cane': '🐶',
  'Gatto': '🐱',
  'Coniglio': '🐰',
  'Criceto': '🐹',
  'Topo': '🐭',
  'Ratto': '🐭',
  'Cavia': '🐾',
  'Furretto': '🦡',
  'Pappagallo': '🦜',
  'Canarino': '🐦',
  'Tartaruga': '🐢',
  'Serpente': '🐍',
  'Iguana': '🦎',
  'Pesce': '🐠',
  'Cavallo': '🐴',
  'Capra': '🐐',
  'Pecora': '🐑',
}

export const BREEDS_BY_SPECIES: Record<string, string[]> = {
  'Cane': [
    'Meticcio',
    'Labrador Retriever', 'Golden Retriever', 'Pastore Tedesco', 'Bulldog Francese',
    'Barboncino Toy', 'Barboncino Nano', 'Barboncino Standard',
    'Beagle', 'Rottweiler', 'Boxer', 'Chihuahua', 'Husky Siberiano',
    'Maltese', 'Yorkshire Terrier', 'Shih Tzu', 'Dalmata',
    'Border Collie', 'Bracco Italiano', 'Volpino di Pomerania',
    'American Pit Bull Terrier', 'Staffordshire Bull Terrier',
    'Setter Irlandese', 'Setter Inglese', 'Cocker Spaniel Inglese',
    'Cocker Spaniel Americano', 'Springer Spaniel',
    'Dobermann', 'Alano', 'Bovaro del Bernese', 'San Bernardo',
    'Terranova', 'Leonberger', 'Pastore Maremmano', 'Pastore Belga',
    'Pastore Australiano', 'Australian Cattle Dog',
    'Jack Russell Terrier', 'West Highland White Terrier', 'Cairn Terrier',
    'Schnauzer Nano', 'Schnauzer Medio', 'Schnauzer Gigante',
    'Bulldog Inglese', 'Carlino', 'Bassotto', 'Bassetto',
    'Chow Chow', 'Akita Inu', 'Shiba Inu', 'Shar Pei',
    'Samoyedo', 'Alaskan Malamute', 'Groenlandese',
    'Weimaraner', 'Vizsla', 'Rhodesian Ridgeback',
    'Greyhound', 'Whippet', 'Levriero Italiano', 'Saluki',
    'Bichon Frisé', 'Bolognese', 'Havanese', 'Spitz Nano',
    'Cane Corso', 'Mastino Napoletano', 'Dogo Argentino',
    'Senza razza definita',
  ],
  'Gatto': [
    'Meticcio / Europeo Comune',
    'Maine Coon', 'Persiano', 'Siamese', 'Bengala',
    'Ragdoll', 'Sphynx', 'British Shorthair', 'British Longhair',
    'Scottish Fold', 'Scottish Straight',
    'Abissino', 'Certosino', 'Norvegese delle Foreste',
    'Burmese', 'Birmano', 'Orientale', 'Balinese',
    'Tonkinese', 'Somalo', 'Angora Turco', 'Van Turco',
    'Russian Blue', 'Nebelung', 'Korat',
    'Savannah', 'Serengeti', 'Chausie',
    'Devon Rex', 'Cornish Rex', 'Selkirk Rex',
    'Munchkin', 'American Curl', 'Manx',
    'Occicat', 'Egyptian Mau', 'Sokoke',
    'Himalayano', 'Exotic Shorthair',
    'Ragamuffin', 'Pixiebob',
    'Senza razza definita',
  ],
  'Coniglio': [
    'Meticcio',
    'Nano Colorato', 'Nano del Polo', 'Ariete Nano', 'Ariete Francese',
    'Angora Inglese', 'Angora Francese', 'Angora Gigante',
    'Rex', 'Mini Rex', 'Lionhead', 'Lop Inglese', 'Lop Francese',
    'Lop Olandese', 'Lop Americano', 'Lop Ariete',
    'Gigante Fiammingo', 'Gigante Grigio', 'Gigante Bianco',
    'Olandese', 'California', 'Nuova Zelanda',
    'Cincillà', 'Havana', 'Satin', 'Velluto Raso',
    'Polish', 'Himalayano', 'Silver',
  ],
  'Criceto': [
    'Criceto Dorato (Siriano)', 'Criceto Russo (Djungarian)',
    'Criceto di Campbell', 'Criceto Cinese', 'Roborowski',
  ],
  'Cavia': [
    'Pelo Liscio (Americano)', 'Pelo Ruvido (Abissino)',
    'Pelo Lungo (Peruviano)', 'Teddy', 'Rex', 'Coronet',
    'Silkie', 'Texel', 'Merino', 'Skinny (Nudo)',
  ],
  'Furretto': [
    'Albino', 'Sable', 'Cioccolato', 'Champagne',
    'Dark-Eyed White', 'Silver', 'Roan', 'Panda',
    'Blaze', 'Mitt', 'Angora',
  ],
  'Pappagallo': [
    'Cocorita', 'Inseparabile', 'Pappagallo Grigio Africano',
    'Ara Macao', 'Ara Blu e Giallo', 'Ara Verde',
    'Cacatua Bianco', 'Cacatua Galerita', 'Cacatua Rosa',
    'Caique Testanera', 'Caique Testobianca',
    'Lorichetto Arcobaleno', 'Ecletto', 'Pionus',
    'Amazzone Fronte Gialla', 'Amazzone Fronte Blu',
    'Conuro Verde', 'Conuro Sole', 'Conuro Ciliegia',
    'Parrocchetto Monaco', 'Parrocchetto Alessandrino',
    'Parrocchetto dal Collare',
  ],
  'Canarino': [
    'Canarino di Canto (Harz)', 'Canarino Belga',
    'Canarino Lizard', 'Canarino di Colore', 'Canarino di Forma',
    'Norwich', 'Yorkshire', 'Gloster', 'Frill',
  ],
  'Tartaruga': [
    'Tartaruga di Hermann', 'Tartaruga Marginata',
    'Tartaruga Greca (Moresca)', 'Tartaruga delle Steppe',
    'Tartaruga dalle Orecchie Rosse', 'Tartaruga Palustre Europea',
    'Tartaruga Scatola', 'Tartaruga Leopardo',
  ],
  'Cavallo': [
    'Purosangue Inglese', 'Purosangue Arabo', 'Andaluso',
    'Lusitano', 'Frisone', 'Shire', 'Clydesdale',
    'Quarter Horse', 'Paint Horse', 'Appaloosa',
    'Morgan', 'Tennesse Walking Horse', 'Haflinger',
    'Lipizzano', 'Hanoveriano', 'KWPN (Olandese da Sella)',
    'Trakehner', 'Warmblood Oldenburgese', 'Selle Français',
    'Pony Shetland', 'Pony Gallese', 'Pony delle Highlands',
    'Mustang', 'Paso Fino', 'Maremmano', 'Murgese',
  ],
}

export const EXPENSE_CATEGORIES = [
  { value: 'vet', label: 'Veterinario' },
  { value: 'food', label: 'Cibo' },
  { value: 'grooming', label: 'Toelettatura' },
  { value: 'toys', label: 'Giochi e accessori' },
  { value: 'medicine', label: 'Farmaci' },
  { value: 'other', label: 'Altro' },
] as const
